NLua/NLua

index.html

Using "as" keyword requires the type be nullable (and double is not).  Changed to "double?" so developers could still perform a null check if desired.

Change C# "double" to "double?"

---

Core/NLua/Lua.cs

Need to remove the translator from the global dictionary before LuaState is closed to avoid race condition, where another LuaState instance can be created at the same address and added to the dictionary before the old one is removed.

  Remove translator from the global pool before Lua state is closed

---

Core/NLua/LuaLib/LuaLib.cs
tests/LuaTests.cs

This is effectively fix for issue #48.
In current implementation, if I call `DoString` with Unicode characters, all characters will be marshaled with `CharSet.Ansi`. It effectively will convert all unicode characters to ANSI '?' (question mark).
Using `Encoding.UTF8.GetBytes()` will convert source string to correct bytes for chunk.
I agreed with http://utf8everywhere.org/ and belive that UTF8 is right encoding for all.

fix unicode characters support in DoString

---

Core/NLua/Extensions/GeneralExtensions.cs

When I was trying to use some extensions method from my project in Lua script I running into problem, cause extensions method was written for interface, not for type.
Example:
```
public class UsedInLua
{
public string DoStuff()
{
return "DoStuff";
}
}
public static class UsedInLuaExtentions
{
public static void DoStuff2(this UsedInLua dostuff)
{
Console.WriteLine("DoStuff2");
}
}
...
lua["usedInLua"] = new UsedInLua();
lua.DoString("str = usedInLua.DoStuff2()");
```
is working.  But this code:
```
public interface IUsedInLua
{
string DoStuff();
}
public class UsedInLua : IUsedInLua
{
public string DoStuff()
{
return "DoStuff";
}
}
public static class UsedInLuaExtentions
{
public static void DoStuff2(this IUsedInLua dostuff)
{
Console.WriteLine("DoStuff2");
}
}
```
was throwed with error …

Finding extention methods by interface too

---

Core/NLua/Metatables.cs
tests/LuaTests.cs
tests/TestLua.cs

When someone registers method print with params array parameters which declaration might look like:
`public static void Print(params object[] data)`
Then he provide lua code  like:
`print(nil, nil)`
He will get error:
`invalid arguments to method call`
This change is only modification to order of checking parameter types. First IsParamsArray, then IsTypeCorrect.  IsParamsArray verifies ParamsAttribute and if present it must be last argument so change should not disturb execution.
May fix: https://github.com/NLua/NLua/issues/236

Fix of calling methods with 'params' array when nil (null) is used as first one.

---

src/Metatables.cs
tests/src/LuaTests.cs
tests/src/TestLua.cs

* The default parameter check was after typecheck
* Fixes https://github.com/NLua/NLua/issues/273

* Fixed issue with default paramers.

---

.editorconfig
NLua.sln
src/CheckType.cs
src/Lua.cs
src/LuaRegistrationHelper.cs
src/Metatables.cs
src/ObjectTranslator.cs
tests/src/CodeGenTests.cs
tests/src/LoadFileTests.cs
tests/src/LuaTests.cs
tests/src/NLuaTest.Shared.Scripts.projitems
tests/src/TestTypes/MyClass.cs
tests/src/TestTypes/TestClass.cs

Added support to Lua integers.
* Operator [] and `GetNumber` will still return the `double` regardless of the value for backward compatibility
LuaTable.GetObject may have breaks if your code is assuming the value will be always a double boxed.
To get long from Lua object use `GetLong` and to get an integer `GetInteger`.

Lua integer support

---

src/Metatables.cs
tests/src/LuaTests.cs

* Related with #340 it seems .NET Core is crashing the process when there is a exception with native/manage frames.

Fixes an issue accessing an Enum array.

---

src/Lua.cs
src/Metatables.cs
src/Method/LuaMethodWrapper.cs
src/ObjectTranslator.cs
tests/src/LuaTests.cs

* Lua.Error() will call setjmp and this can cause a crash with CLR on Linux, it seems that calling the setjmp longjmp twice will crash on *nix systems.
This should make this issue work a bit better: https://github.com/NLua/NLua/issues/344

Move call to `lua_error` to the same level of the delegate callback

---

src/CheckType.cs
src/Metatables.cs
src/Method/LuaMethodWrapper.cs
tests/src/LuaTests.cs

* Guid has a lot of ctor overload, the `byte[]` was being used instead the `string`.
Reorder ctor info before trying to match the parameters.

Fixed  #355 new Guid

---

README.md

Clicking on the logo would 404 at https://github.com/NLua/NLua/blob/master. This makes it redirect to https://github.com/NLua/NLua.

Fix broken logo link

---

README.md

Example of converting a Lua global to a double should use a cast.

Update to example code

---

src/Lua.cs
tests/build/net45/NLuaTest.csproj
tests/src/LuaTests.cs

This PR addresses the issue where you need to give a large object with many child methods as a global variable but want to restrict the amount of up front reflection that happens (for performance).
https://github.com/NLua/NLua/issues/366
I have used System.DataTable in the test since it is a good complex class with self referencing properties.  
Setting `MaximumRecursion` to 0 on an instance of `Lua` results in only a single global being created and no reflection exploration happening (see TestMaximumRecursion).

Use configurable MaximumRecursion

---

src/CheckType.cs
tests/src/LuaTests.cs
tests/src/TestTypes/TestClass.cs

For a function on a net object with string parameters, the 'extractor' for a null string would return an object type.  This extractor is cached, and on the next invocation, a non-null string parameter would try to be extracted as an object type, which would cause a failure.

Fix Parameter Matching for String Parameters on Null Caching

---

src/CheckType.cs
tests/src/LuaTests.cs
tests/src/TestTypes/TestClass.cs

The fix addresses the issue of a wrong overloaded method identification where the numeric overload is confused with string one in a case the string represent numeric value, e.g.
void foo(uint32) -> foo(1)
void foo(string) -> foo('1')
Check the the type to be numeric rather than a number: IsNumericType. The side effect of IsNumber check causes numeric strings to be treated as numbers which leads to wrong overloaded method identification.

Fix the overloaded methods issue

---

NLua.net5.0.sln
src/GenerateEventAssembly/CodeGeneration.cs

Fixed bug where calling a method returning void through reflection threw an InvalidProgramException.
After calling the base method and/or the overriding method, the generated code would pop, trying to discard the return value, but since void methods don't push a return value onto the stack, the code would pop on the empty stack, causing a crash.

MethodInfo.Invoke on void method crash fix

---

src/Metatables.cs

Avoid Convert throwing InvalidCastException if table includes objects of classes that does not implement IConvertible.

only convert IConvertible

---

.gitignore
src/Lua.cs
src/LuaGlobals.cs
src/NLua.Shared.projitems
tests/src/LuaTests.cs
tests/src/NLuaTest.Shared.projitems
tests/src/TestTypes/GlobalsTestClass.cs

Fix for https://github.com/NLua/NLua/issues/468
Basically the following code will lead to a massive slowdown in performance:
```
Lua lua = new Lua();
for (int i = 0; i < 1_000_000; i++)
{
lua["obj"] = new SomeObject(); // <-- This seems to slow things down
// lua.DoString("return 2 * obj:SomeMethod()"); // <-- commented to show you don't even need to run a Lua script to trigger the slowdown.
if (i % 1000 == 0)
{
Console.WriteLine($"{1_000_000 - i} remaining");
}
}
class SomeObject
{
public int SomeMethod()
{
return 2;
}
}
```
This happens because the `_globals` in the `Lua` class do not get properly cleaned up if you overwrite a C# object. In this case the same globals are added on top of the already existing globals leading to a list of `_globals` with thousands of elements.
This issue …

Moved Lua _globals to a separate class (this class includes a fix for #468)

---

src/Metatables.cs
src/Method/LuaMethodWrapper.cs
src/ObjectTranslator.cs
tests/src/LuaTests.cs
tests/src/TestTypes/TestClass.cs

When a Lua table was provided as an argument to a params array parameter, all values were extracted and added to an array of the expected type. Example:
`func(true, false)`
`func{true, false} -- a table!`
Both invocations were translated to the same number of arguments.
This lead to errors when providing further arguments (besides the initial table). See #463, #466
Tables are handled like any other type. The code for unpacking a Lua table has been removed from _Metatables.TableToArray_. This method was and **is** responsible for extracting all Lua provided arguments, converting them to C# types and add them to an array (the argument for the params-array-parameter). As the 'unpacking of tables'-part is now gone, it was renamed to 'CreateParamsArray' to better reflect what it actually does. …

Changed the handling of variadic arguments.

---

src/Method/LuaMethodWrapper.cs
src/ObjectTranslator.cs
tests/src/LuaTests.cs
tests/src/TestTypes/TestClass.cs

Additional return values were supported by means of out/ ref paramters only.
A returned _ValueTuple_ (all _ITuple_ implementing value types, actually) gets special treatment by returning all elements of the tuple instead of the tuple itself. The returned values preceed all ref/ out parameters.
The old way of returning multiple values is still supported.
Implementations which expect ValueTuples to be returned as a single object might break.
Would fix: #458

Added support for multiple return values via ValueTuple

---

src/Lua.cs
src/LuaGlobals.cs
tests/src/LuaTests.cs

This PR fixes #480 that I posted earlier, by applying the suggested changes. In addition to the suggested changes, for the following to work, some more work had to be done to the indexer for `Lua`.
```c#
lua["testFunc"] = testFunc.Method;
```
It first checks to see if the value that is being assigned is assignable to the `MethodBase` type, and if it is, then it will handle it as registering a function instead.
@viniciusjarina Any thoughts on the changes?

Registering functions now only register 1 global, fix #480

---

src/CheckType.cs
src/Method/LuaMethodWrapper.cs
tests/src/LuaTests.cs
tests/src/TestTypes/TestClassWithGenericMethod.cs

Added support for generic class parameters for generic methods, and now Linq methods, IEnumerable, Dictionary, and more can be used.

Added support for generic class parameters for generic methods

---

src/Lua.cs

Set debug hook should return -1 only if hook is already set. but it is currently returning -1 anyway.
let's return 0 for a successful set.

Set debug hook fix

---

src/Lua.cs
src/LuaBase.cs
src/Metatables.cs
src/Method/LuaMethodWrapper.cs
src/ObjectTranslator.cs
src/ObjectTranslatorPool.cs
tests/src/LuaTests.cs

Lua instances end up being permanently rooted until Dispose is explicitly called, because the ctor roots the Lua instance into a static singleton of ObjectTranslatorPool. ~~This fixes it by replacing the ConcurrentDictionary with a ConditionalWeakTable, in order to avoid the pool keeping a strong reference to the LuaState / Lua objects.~~ This fixes it by making ObjectTranslator's reference to the associated Lua object a weak reference.

Fix finalizability of Lua instances
